package helloCorba;

/**
* helloCorba/HelloHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/helloWorld.idl
* Quinta-feira, 12 de Janeiro de 2006 15h53min27s GMT-03:00
*/

public final class HelloHolder implements org.omg.CORBA.portable.Streamable
{
  public helloCorba.Hello value = null;

  public HelloHolder ()
  {
  }

  public HelloHolder (helloCorba.Hello initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = helloCorba.HelloHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    helloCorba.HelloHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return helloCorba.HelloHelper.type ();
  }

}
