package helloCorba;


/**
* helloCorba/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/helloWorld.idl
* Quinta-feira, 12 de Janeiro de 2006 15h53min27s GMT-03:00
*/

public interface HelloOperations 
{
  String sayHello (String msg);

  // This line is an operation statement.
  void shutdown ();
} // interface HelloOperations
