package helloCorba;


/**
* helloCorba/Hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/helloWorld.idl
* Quinta-feira, 12 de Janeiro de 2006 15h53min27s GMT-03:00
*/

public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hello
