#! /bin/bash

#
# This script is a wrapper for the TimeSys JVM so that we may integrate
# it with the Junit task def from within the Ant build file
#
# To use the Sun JVM, uncomment the appropriate line
# 

#
# We need to tweak a lot of nonsense for tjvm to work fine - it is simply crazy !
#
export IMMORTAL_SIZE=10000000


# For TimeSys JVM
#
# Note that the environment variable TJVM_BOOT_PATH must point to the foundation.jar file
#

#exec tjvm -Djava.class.path=$CLASSPATH -Xbootclasspath:$TJVM_BOOT_PATH $3 $4 $5 $6 $7 $8 $9 

# For Sun JVM
exec java $*
