!/////////////////////////////////////////////////////////////////////////
!// file: global_variables.inc                                          //
!// This file is distributed as part of OpenSTA - http://opensta.org/   //
!// It is included in all generated scripts and is intended to contain  //
!// user defined variables and constants required at a global scope.    //
!/////////////////////////////////////////////////////////////////////////
