/*
* Copyright (C) The Community OpenORB Project. All rights reserved.
*
* This software is published under the terms of The OpenORB Community Software
* License version 1.0, a copy of which has been included with this distribution
* in the LICENSE.txt file.
*/

module org
{
    module openorb
    {
        module orb
        {
            module examples
            {
                module messaging
                {
                    interface ITimeout
                    {
                        void waitForTimeout( in long msec );
                    };
                };
            };
        };
    };
};

