// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __Consumer__
#define __Consumer__

#pragma interface

#include <edu/wustl/doc/facet/EventChannelPushConsumer.h>

extern "Java"
{
  class Consumer;
  namespace edu
  {
    namespace wustl
    {
      namespace doc
      {
        namespace facet
        {
          namespace EventComm
          {
            class Event;
          }
        }
      }
    }
  }
};

class ::Consumer : public ::edu::wustl::doc::facet::EventChannelPushConsumer
{
public:
  virtual void push (::edu::wustl::doc::facet::EventComm::Event *);
  Consumer ();

  static ::java::lang::Class class$;
};

#endif /* __Consumer__ */
