// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __TestLauncher__
#define __TestLauncher__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  class TestLauncher;
};

class ::TestLauncher : public ::java::lang::Object
{
private:
  static void testLogic (JArray< ::java::lang::String *> *);
public:
  static void main (JArray< ::java::lang::String *> *);
  TestLauncher ();

  static ::java::lang::Class class$;
};

#endif /* __TestLauncher__ */
