CREATE TABLE CONFIGURATION(
id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1000) PRIMARY KEY,
   name VARCHAR(32),
   UNIQUE(name)
);

CREATE TABLE CONNECTION (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1000) PRIMARY KEY,
    name VARCHAR(64),
    url VARCHAR(64),
    hostname VARCHAR(32),
    port VARCHAR(8),
    protocol VARCHAR(16),
    UNIQUE(name)
);

INSERT INTO CONNECTION(name, url, hostname, port, protocol) values ('local','local:glassbox','localhost','0','local');

CREATE TABLE MAILSERVER (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1000) PRIMARY KEY,
	name VARCHAR(64),
    smtp VARCHAR(64),
    userName VARCHAR(64),
    password VARCHAR(32),
    UNIQUE(userName)
);