/*
* Copyright (C) The Community OpenORB Project. All rights reserved.
*
* This software is published under the terms of The OpenORB Community Software
* License version 1.0, a copy of which has been included with this distribution
* in the LICENSE.txt file.
*/

module org
{
    module openorb
    {
        module orb
        {
            module examples
            {
                module idl
                {
                    module reflection
                    {
                        typePrefix reflection "openorb.org";

                        /**
                         * This interface is provided for the OpenORB IDL Reflection example.
                         */
                        interface MyInterface1
                        {
                            /**
                             * This attribute is provided for the OpenORB IDL Reflection example.
                             */
                            readonly attribute string myAttr1;

                            /**
                             * This attribute is provided for the OpenORB IDL Reflection example.
                             */
                            attribute long myAttr2;

                            /**
                             * This operation is provided for the OpenORB IDL Reflection example.
                             */
                            void myOperation1();
                        };

                        /**
                         * This interface is provided for the OpenORB IDL Reflection example.
                         */
                        interface MyInterface2
                        {
                            /**
                             * This operation is provided for the OpenORB IDL Reflection example.
                             */
                            void myOperation2();
                        };
                    };
                };
            };
        };
    };
};
