// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package exemplo2;

public final class ComunicacaoImpl_Stub
    extends java.rmi.server.RemoteStub
    implements exemplo2.Comunicacao, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_receive_0;
    private static java.lang.reflect.Method $method_send_1;
    
    static {
	try {
	    $method_receive_0 = exemplo2.Comunicacao.class.getMethod("receive", new java.lang.Class[] {exemplo2.Mensagem.class});
	    $method_send_1 = exemplo2.Comunicacao.class.getMethod("send", new java.lang.Class[] {exemplo2.Mensagem.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public ComunicacaoImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of receive(Mensagem)
    public void receive(exemplo2.Mensagem $param_Mensagem_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_receive_0, new java.lang.Object[] {$param_Mensagem_1}, -3061117833274146430L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of send(Mensagem)
    public void send(exemplo2.Mensagem $param_Mensagem_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_send_1, new java.lang.Object[] {$param_Mensagem_1}, -1519348875554247426L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
