/*
* Copyright (C) The Community OpenORB Project. All rights reserved.
*
* This software is published under the terms of The OpenORB Community Software
* License version 1.0, a copy of which has been included with this distribution
* in the LICENSE.txt file.
*/
#ifndef __JAVA_IDL_IDL_FROM_JAVA__
#define __JAVA_IDL_IDL_FROM_JAVA__

// -------------------------------------------------------
// Module java
// -------------------------------------------------------

module java
{
	// -------------------------------------------------------
	// Module lang
	// -------------------------------------------------------

	module lang
	{
		// -------------------------------------------------------
		// TypeDef _Object
		// -------------------------------------------------------

		typedef any _Object;

 		// -------------------------------------------------------
 		// ValueType Throwable
 		// -------------------------------------------------------
 
 		valuetype Throwable
 		{
 		};
 
 		// -------------------------------------------------------
 		// Exception ThrowableEx
 		// -------------------------------------------------------
 
 		exception ThrowableEx
 		{
 		   Throwable value;
 		};
 
 		// -------------------------------------------------------
 		// ValueType Exception
 		// -------------------------------------------------------
 
 		valuetype _Exception : ::java::lang::Throwable
 		{
 		};
 
 
 		// -------------------------------------------------------
 		// Exception Ex
 		// -------------------------------------------------------
 		exception Ex
 		{
 		   _Exception value;
 		};
 

	};

	// -------------------------------------------------------
	// Module io
	// -------------------------------------------------------

	module io
	{
		// -------------------------------------------------------
		// TypeDef Serializable
		// -------------------------------------------------------

		typedef any Serializable;

		// -------------------------------------------------------
		// TypeDef Externalizable
		// -------------------------------------------------------

		typedef any Externalizable;

	};

	// -------------------------------------------------------
	// Module rmi
	// -------------------------------------------------------

	module rmi
	{
		// -------------------------------------------------------
		// TypeDef Remote
		// -------------------------------------------------------

		typedef Object Remote;

	};

};

#endif
