/*
* Copyright (C) The Community OpenORB Project. All rights reserved.
*
* This software is published under the terms of The OpenORB Community Software
* License version 1.0, a copy of which has been included with this distribution
* in the LICENSE.txt file.
*/
#ifndef __JAVAX_IDL_IDL_FROM_JAVA__
#define __JAVAX_IDL_IDL_FROM_JAVA__

// -------------------------------------------------------
// Module javax
// -------------------------------------------------------

module javax
{
	// -------------------------------------------------------
	// Module rmi
	// -------------------------------------------------------

	module rmi
	{
		// -------------------------------------------------------
		// Module CORBA
		// -------------------------------------------------------

		module CORBA
		{
			// -------------------------------------------------------
			// ValueType ClassDesc
			// -------------------------------------------------------

			valuetype ClassDesc
			{
			};

		};

	};

};

#endif
