// File: CORBA_CustomMarshal.idl
// CORBA 2.3, Chapter 5

#ifndef _CORBA_CustomMarshal_IDL_
#define _CORBA_CustomMarshal_IDL_

#include "CORBA_Stream.idl"

#pragma prefix "omg.org"

module CORBA 
{

    valuetype StringValue string;
    valuetype WStringValue wstring;

    abstract valuetype CustomMarshal 
    {
        void marshal ( in DataOutputStream os );
        
        void unmarshal ( in DataInputStream is );
    };

};

#endif // _CORBA_CustomMarshal_IDL_
