/*
* Copyright (C) The Community OpenORB Project. All rights reserved.
*
* This software is published under the terms of The OpenORB Community Software
* License version 1.0, a copy of which has been included with this distribution
* in the LICENSE.txt file.
*/

// This file includes other files containing omg defined local interfaces

// includes TimeBase.idl
#include "Messaging.idl"

#include "PortableServer.idl"

#include "DynamicAny.idl"

// Added by the portable interceptors submission

#include "Codec.idl"
#include "Dynamic.idl"
#include "PortableInterceptor.idl"
