/*
* Copyright (C) The Community OpenORB Project. All rights reserved.
*
* This software is published under the terms of The OpenORB Community Software
* License version 1.0, a copy of which has been included with this distribution
* in the LICENSE.txt file.
*/

// This file includes all openorb sepcific idl files

#include "OpenORB_policy.idl"

#include "OpenORB_corbaloc.idl"
