/*
* Copyright (C) The Community OpenORB Project. All rights reserved.
*
* This software is published under the terms of The OpenORB Community Software
* License version 1.0, a copy of which has been included with this distribution
* in the LICENSE.txt file.
*/

#ifndef _TEST_DSI_IDL_
#define _TEST_DSI_IDL_

#pragma prefix "openorb.org"

module orb
{
    module test
    {
        module dynamic
        {
            interface DSITarget
            {
                exception DivideByZero
                {};

                float divide( in float nb1, in float nb2 ) raises ( DivideByZero );
            };
        };
    };
};

#endif
