// $Id: ServerKiller.idl,v 1.2 2003/08/19 22:29:58 ravip Exp $

module edu {
module wustl {
module doc {
module utils {
  
        interface ServerKiller
        {
                oneway void shutdown ();
        };

}; 
}; 
};
};
